// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ConvertRequest struct {
	LongUrl string `json:"longUrl" validate:"required"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}

type DailyStats struct {
	Date           string `json:"date"`
	Clicks         int64  `json:"clicks"`
	UniqueVisitors int64  `json:"uniqueVisitors"`
}

type ShortUrlStatsRequest struct {
	ShortUrl  string `path:"shortUrl" validate:"required"`
	StartDate string `form:"startDate"`
	EndDate   string `form:"endDate"`
}

type ShortUrlStatsResponse struct {
	TotalClicks         int64        `json:"totalClicks"`
	TotalUniqueVisitors int64        `json:"totalUniqueVisitors"`
	DailyStats          []DailyStats `json:"dailyStats"`
}

type ShowRequest struct {
	ShortUrl string `path:"shortUrl" validate:"required"`
}

type ShowResponse struct {
	LongUrl string `json:"longUrl"`
}
