// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"shortener/internal/svc"
	"shortener/pkg/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 创建中间件链
	commonMiddleware := middleware.Chain(
		middleware.WithRequestContext(),
		middleware.WithAccessLog(),
		middleware.WithRateLimiter(1000), // 每秒限制1000个请求
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:shortUrl",
				Handler: commonMiddleware(ShowHandler(serverCtx)),
			},
			{
				Method:  http.MethodPost,
				Path:    "/convert",
				Handler: commonMiddleware(ConvertHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/stats/:shortUrl",
				Handler: commonMiddleware(ShortUrlStatsHandler(serverCtx)),
			},
		},
	)
}
